-- +goose Up
-- +goose StatementBegin
CREATE TABLE IF NOT EXISTS skills (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) UNIQUE
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE skills;
-- +goose StatementEnd
